### ISSUE TITLE
Add method for as-cheaply-as-possible determining existence of upstream project

### ISSUE THREAD

**Issue by sdboyer** [Masterminds/vcs#22]
A method that is designed solely for determining the existence of the upstream project as cheaply as possible would be invaluable for careful performance optimizations in `vsolver`.

**Comment by sdboyer** [comment]
Just to be clear, this method should *not* require the existence of any local on-disk state.

**Comment by mattfarina** [comment]
With the merger of PR #23 this should be complete.
