### ISSUE TITLE
isDetachedHead fails with non-english locales

### ISSUE THREAD

**Issue by DirtyHairy** [Masterminds/vcs#29]
isDetachedHead parses `git status` output and looks for "HEAD detached at" Obviously, this fails for any non-english locale. I don't want to be a dick, but this is insanely brittle :smirk:

A possible improvement would be resetting `LANG` before running git. An even better solution would be checking the contents of `.git/HEAD` &mdash; this would avoid breakage from future changes of this message. I can provide a pull request if any of these changes would be OK with you.

**Comment by mattfarina** [comment]
@DirtyHairy you don't have to be a dick to point out a bug. I've written plenty of them.

**Comment by DirtyHairy** [comment]
:smile: I was just trying to take the edge away from "insanely brittle". Anyway, the fix is easy enough, if you like, I can implement it and file a pull request.

**Comment by mattfarina** [comment]
@DirtyHairy in #32 I already proposed a fix. Any feedback?

**Comment by DirtyHairy** [comment]
Looks good to me.
