### ISSUE TITLE
running concurrent checks on multiple repos does not always work

### ISSUE THREAD

**Issue by jlargent** [Masterminds/vcs#6]
I'm trying to work with multiple git repos at the same but am having issues.
3 git repos all hosted on github.

```go
package main

import (
	"log"
	"sync"

	"github.com/Masterminds/vcs"
)

var (
	base = "/srv/apps/"
)

func main() {
	var (
		dirs    = []string{"a", "b", "c"}
		release = "release/4.1.0"
		remotes = map[string]string{
			"a": "git@github.com:fake/a.git",
			"b": "git@github.com:fake/b.git",
			"c": "git@fake/c.git",
		}
	)

	pg := new(sync.WaitGroup)
	for _, val := range dirs {
		pg.Add(1)
		go updateRepo(val, remotes[val], release, pg)
	}
	pg.Wait()
}

func updateRepo(local string, remote string, rel string, pg *sync.WaitGroup) {
	local = base + local

	log.Printf("%s -- %s -- %s\n", local, remote, rel)

	repo, err := vcs.NewGitRepo(remote, local)
	if err != nil {
		log.Printf("In Error: %s -- %s -- %s\n", local, remote, rel)
		log.Fatalln(err)
	}
	if repo.CheckLocal() {
		log.Printf("Local good: %s\n", local)
	}

	pg.Done()
}
```

I would expect this output everytime(assuming all git repos are there)

2015/10/19 11:59:02 /srv/apps/c -- git@github.com:fake/c.git -- release/4.1.0
2015/10/19 11:59:02 /srv/apps/a -- git@github.com:fake/a.git -- release/4.1.0
2015/10/19 11:59:02 /srv/apps/b -- git@github.com:fake/b.git -- release/4.1.0
2015/10/19 11:59:02 Local good: /srv/apps/c
2015/10/19 11:59:02 Local good: /srv/apps/a
2015/10/19 11:59:02 Local good: /srv/apps/b

However I sometimes I get this:

2015/10/19 11:58:40 /srv/apps/c -- git@github.com:fake/c.git -- release/4.1.0
2015/10/19 11:58:40 /srv/apps/a -- git@github.com:fake/a.git -- release/4.1.0
2015/10/19 11:58:40 /srv/apps/valuation -- git@github.com:fake/b.git -- release/4.1.0
2015/10/19 11:58:40 Local good: /srv/apps/c
2015/10/19 11:58:40 In Error: /srv/apps/a -- git@github.com:fake/a.git -- release/4.1.0
2015/10/19 11:58:40 The Remote does not match the VCS endpoint

**Comment by jlargent** [comment]
I took the time to look at how you are doing the CheckLocal, and it was the same issue I was having with
the code I am currently using. It's the os.Chdir().
I guess I need to figure out how to spawn a separate shell to run each process in if I want it to run concurrently.

**Comment by mattfarina** [comment]
This, I would say, is a bug. You should be able to do concurrent work. I'll fix this. Thanks for bringing it up.

**Comment by mattfarina** [comment]
@jlargent can you try the latest on master and see if that fixes your problem.

**Comment by jlargent** [comment]
Yes it did, thank you.
I was actually testing the same fix. "getting rid of os.Chdir()"
