### ISSUE TITLE
Failed to do initial checkout of config: Cannot detect VCS for google.golang.org/grpc

### ISSUE THREAD

**Issue by penhauer-xiao** [Masterminds/vcs#66]
As title

**Comment by mattfarina** [comment]
@penhauer-xiao where did you see that? Did that come out of Glide?

google.golang.org provides a go-get redirect. Glide and the vcs lib know how to read them. But, if that service goes offline (which sometimes happens) issues occur. Did the problem go away?

**Comment by penhauer-xiao** [comment]
I know the reason is really network, thank you
