### ISSUE TITLE
VCS-76: Something hosed w git submodules handling

### ISSUE THREAD

**Issue by m0j0hn** [Masterminds/vcs#76]
I am trying to use Glide on Linux and Windows, and for one of my modules with submodules, it's failing on Windows. Some Googling revealed Glide issue #745, which referenced line 388 in git.go.
After manually trying the underlying git commands on my Windows, I think root cause is that "git submodule foreach ... --prefix=..." passes the prefix string as a doublequote delimited string to Windows bash, and the trailing '\' (Windows PathDelimiter) *escapes* the closing doublequote, which Breaks Things (tm). My inelegant solution is to create helper function which is used to conditionally rewrite the path string on Windows by tripling every PathDelimiter, i.e., '\' becomes '\\\' - and this seems to solve the problem. I also added another test using a publicly accessible repo which exercised the original problem which led me to work on this in the first place.

**Comment by m0j0hn** [comment]
@mattfarina @technosophos Can you please consider this Issue and the PR for its fix?
https://github.com/Masterminds/vcs/pull/77

**Comment by mattfarina** [comment]
I merged the PR. I'll update glide in the next couple days when I get a moment.
