### ISSUE TITLE
Bitbucket v1 API is no more

### ISSUE THREAD

**Issue by freeformz** [Masterminds/vcs#98]
https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/

This is used [here](https://github.com/Masterminds/vcs/blob/b4f55832432b95a611cf1495272b5c8e24952a1a/vcs_remote_lookup.go#L247) and will return a 410.

**Comment by mattfarina** [comment]
Thanks. Just merged in a fix. Updates across the board coming soon.
